---
version: '3.7'
services:
#  nginx:
#    image: nginx:1.25.3
#    restart: no
#    volumes:
#      - ./nginx/templates:/etc/nginx/templates
#      - ./nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
#    ports:
#      - "80:80"
#    networks:
#      - yas-network

  #  product:
  #    build: ./product-service
  #    image: ghcr.io/nashtech-garage/yas-product:latest
  #    environment:
  #        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/productservice?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
  #        SPRING_DATASOURCE_USERNAME: root
  #        SPRING_DATASOURCE_PASSWORD: root

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - yas-network

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - yas-network
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - yas-network
  identity:
    image: quay.io/keycloak/keycloak:21.0.2
    command: [ 'start-dev', '--import-realm' ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: passthrough
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysqlcontainer:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_HTTP_PORT: 80
    ports:
      - "81:80"
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./identity/themes/yas/theme:/opt/keycloak/themes
    networks:
      - yas-network

  mysqlcontainer:
    image: mysql:latest
    restart: always
    container_name: mysqlcontainer
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_PASSWORD: root
    volumes:
      - microservice-ecorrmmer_mysql_db1:/var/lib/mysql
    networks:
      - yas-network

volumes:
  microservice-ecorrmmer_mysql_db1:
    external: true

networks:
  yas-network:
    driver: bridge
    name: yas-network

